services:
  # Backend Service
  - type: web
    name: social-media-post-generator-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python -m gunicorn --bind 0.0.0.0:$PORT --timeout 300 --keep-alive 300 --worker-connections 1000 --worker-class sync src.main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-post-generator-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: TWITTER_CLIENT_ID
        sync: false
      - key: TWITTER_CLIENT_SECRET
        sync: false
      - key: INSTAGRAM_CLIENT_ID
        sync: false
      - key: INSTAGRAM_CLIENT_SECRET
        sync: false

# Database
databases:
  - name: social-media-post-generator-db
    databaseName: social_media_post_generator

